# CMake generated Testfile for 
# Source directory: /root/opencv
# Build directory: /root/opencv/build-4.9
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs("3rdparty/libwebp")
subdirs("3rdparty/openjpeg")
subdirs("3rdparty/ippiw")
subdirs("3rdparty/protobuf")
subdirs("3rdparty/ittnotify")
subdirs("include")
subdirs("modules/.firstpass/calib3d")
subdirs("modules/.firstpass/core")
subdirs("modules/.firstpass/dnn")
subdirs("modules/.firstpass/features2d")
subdirs("modules/.firstpass/flann")
subdirs("modules/.firstpass/gapi")
subdirs("modules/.firstpass/highgui")
subdirs("modules/.firstpass/imgcodecs")
subdirs("modules/.firstpass/imgproc")
subdirs("modules/.firstpass/java")
subdirs("modules/.firstpass/js")
subdirs("modules/.firstpass/ml")
subdirs("modules/.firstpass/objc")
subdirs("modules/.firstpass/objdetect")
subdirs("modules/.firstpass/photo")
subdirs("modules/.firstpass/python")
subdirs("modules/.firstpass/stitching")
subdirs("modules/.firstpass/ts")
subdirs("modules/.firstpass/video")
subdirs("modules/.firstpass/videoio")
subdirs("modules/.firstpass/world")
subdirs("modules/core")
subdirs("modules/flann")
subdirs("modules/imgproc")
subdirs("modules/dnn")
subdirs("modules/features2d")
subdirs("modules/imgcodecs")
subdirs("modules/videoio")
subdirs("modules/calib3d")
subdirs("modules/objdetect")
subdirs("doc")
subdirs("data")
subdirs("apps")
